package com.example.android.ffxivhelper;

public class CollectibleObject {
    private final String collectibleID;
    private final String collectibleName;
    private final int collectibleType;

    public CollectibleObject(String ID, int type) {
        collectibleType = 0; //TODO: support multiple types
        collectibleID = ID;
        collectibleName = mounts[Integer.parseInt(ID)];
    }

    public String getCollectibleID() {
        return collectibleID;
    }

    public String getCollectibleName() {
        return collectibleName;
    }

    public static String[] mounts = {
            "",
            "Company Chocobo",
            "",
            "",
            "Goobbue",
            "Legacy Chocobo",
            "Magitek Armor",
            "",
            "Coeurl",
            "Ahriman",
            "",
            "",
            "",
            "",
            "",
            "Unicorn",
            "",
            "",
            "Behemoth",
            "Cavalry Drake",
            "Laurel Goobbue",
            "Gilded Magitek Armor",
            "Nightmare",
            "",
            "",
            "Fat Chocobo",
            "Cavalry Elbst",
            "Bomb Palanquin",
            "Aithon",
            "Xanthos",
            "Gullfaxi",
            "Enbarr",
            "Warlion",
            "Warbear",
            "Draught Chocobo",
            "Direwolf",
            "Storm Warsteed",
            "Serpent Warsteed",
            "Flame Warsteed",
            "",
            "Markab",
            "Ceremony Chocobo",
            "Sleipnir",
            "Boreas",
            "Parade Chocobo",
            "Black Chocobo",
            "Adamantoise",
            "Kirin",
            "Logistics System",
            "Fenrir",
            "Midgardsormr",
            "",
            "Amber Draught Chocobo",
            "Sanuwa",
            "Griffin",
            "Manacutter",
            "War Panther",
            "",
            "Gobwalker",
            "Twintania",
            "",
            "",
            "Witch's Broom",
            "",
            "",
            "",
            "",
            "Pegasus",
            "White Devil",
            "Red Baron",
            "Wyvern",
            "SDS Fenrir",
            "Kongamato",
            "Zu",
            "Bennu",
            "White Lanner",
            "Rose Lanner",
            "Round Lanner",
            "Warring Lanner",
            "",
            "Gloria-class Airship",
            "Flying Cumulus",
            "Original Fat Chocobo",
            "Astrope",
            "Fat Moogle",
            "",
            "Cloud Mallow",
            "Whisper-go",
            "",
            "",
            "Dark Lanner",
            "Aerodynamics System",
            "Disembodied Head",
            "Managarm",
            "Whisper A-go-go",
            "Goten",
            "Ginga",
            "Mystic Panda",
            "Sophic Lanner",
            "Starlight Bear",
            "Black Pegasus",
            "Arrhidaeus",
            "Raigo",
            "",
            "Demonic Lanner",
            "Firebird",
            "Eggshilaration System",
            "",
            "Lone Hellhound",
            "Pack Hellhound",
            "Archon Throne",
            "Syldra",
            "Falcon",
            "Lone Faehound",
            "Pack Faehound",
            "Blissful Kamuy",
            "Reveling Kamuy",
            "",
            "",
            "",
            "",
            "Magitek Predator",
            "Battle Lion",
            "Battle Bear",
            "Battle Panther",
            "Yol",
            "Alte Roite",
            "Centurio Tiger",
            "",
            "",
            "Ixion",
            "",
            "",
            "Legendary Kamuy",
            "",
            "Nezha Chariot",
            "Striped Ray",
            "",
            "Aquamarine Carbuncle",
            "Citrine Carbuncle",
            "Flying Chair",
            "Magitek Avenger",
            "Korpokkur Kolossus",
            "Red Hare",
            "Auspicious Kamuy",
            "Magitek Death Claw",
            "Marid",
            "",
            "True Griffin",
            "",
            "Tyrannosaur",
            "",
            "Broken Heart (right)",
            "Broken Heart (left)",
            "Typhon",
            "",
            "Air Force",
            "",
            "Lunar Kamuy",
            "Dodo",
            "Indigo Whale",
            "Rathalos",
            "Magitek Conveyor",
            "Prototype Conveyor",
            "Mikoshi",
            "",
            "Juedi",
            "",
            "Safeguard System",
            "",
            "",
            "Fatter Cat",
            "Euphonious Kamuy",
            "Model O",
            "Magitek Sky Armor",
            "Magicked Carpet",
            "Magna Roader",
            "Fat Black Chocobo",
            "Eldthurs",
            "Maxima Roader",
            "Sabotender Emperador",
            "Kamuy Of The Nine Tails",
            "Hallowed Kamuy",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",

    };
}